SELECT      WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') 
# Oracle에서는 NVL(), MySQL에서는 IFNULL() 혹은 IF(), 표준 SQL인 CCOALESCE()는 모든 DB에서 사용 가능.
FROM        FOOD_WAREHOUSE
WHERE       ADDRESS LIKE '%경기도%'
ORDER BY    WAREHOUSE_ID ASC;