SELECT      CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION 
            # 당일 반납의 경우도, 대여 기간을 1일로 간주하므로 DATEDIFF(END_DATE, START_DATE) + 1.
FROM        CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY    CAR_ID # CAR_ID를 기준으로 그룹화.
HAVING      AVERAGE_DURATION >= 7 # 평균 대여 기간이 7일 이상인 행만 필터링.
ORDER BY    AVERAGE_DURATION DESC, CAR_ID DESC; 