SELECT  ITEM_ID, ITEM_NAME, RARITY
FROM    ITEM_INFO
WHERE   ITEM_ID IN (
        -- 서브쿼리를 통해 PARENT_ITEM_ID의 희귀도가 'RARE'인 아이템들의 자식 ID를 조회
        SELECT TR.ITEM_ID
        FROM ITEM_TREE TR JOIN ITEM_INFO NF ON TR.PARENT_ITEM_ID = NF.ITEM_ID
        WHERE NF.RARITY = 'RARE'
        )
ORDER BY ITEM_ID DESC;